name: elearning
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.5+9

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  advance_pdf_viewer: ^2.0.0
  animations: ^2.0.0
  badges: ^2.0.1
  chewie: ^1.2.2
  cupertino_icons: ^1.0.2
  custom_pop_up_menu: ^1.2.0
  dio: ^4.0.0
  equatable: ^2.0.2
  flutter_easyloading: ^3.0.0
  flutter_ringtone_player: ^3.0.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  get: ^4.1.4
  get_storage: ^2.0.2
  hexcolor: ^2.0.3
  json_serializable: ^4.1.3
  package_info: ^2.0.2
  photo_view: ^0.11.1
  video_player: ^2.1.6
  webview_flutter: ^2.0.8
  stop_watch_timer: ^1.3.1
  vibration: ^1.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Newsreader
      fonts:
        - asset: assets/fonts/Newsreader-Regular.ttf
          weight: 500
        - asset: assets/fonts/Newsreader-Medium.ttf
          weight: 500
        - asset: assets/fonts/Newsreader-SemiBold.ttf
          weight: 600
